export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const REGISTER_INSTRUCTOR_REQUEST = "REGISTER_INSTRUCTOR_REQUEST"
export const REGISTER_INSTRUCTOR_SUCCESS = "REGISTER_INSTRUCTOR_SUCCESS"
export const REGISTER_INSTRUCTOR_FAIL = "REGISTER_INSTRUCTOR_FAIL"
