export const STUDENT_COUNT_REQUEST = "STUDENT_COUNT_REQUEST"
export const STUDENT_COUNT_SUCCESS = "STUDENT_COUNT_SUCCESS"
export const STUDENT_COUNT_FAIL = "STUDENT_COUNT_FAIL"

export const ACCOUNT_BAL_REQUEST = "ACCOUNT_BAL_REQUEST"
export const ACCOUNT_BAL_SUCCESS = "ACCOUNT_BAL_SUCCESS"
export const ACCOUNT_BAL_FAIL = "ACCOUNT_BAL_FAIL"
