export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST"
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL"

export const LOAD_COURSES_REQUEST = "LOAD_COURSES_REQUEST"
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS"
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL"

export const LOAD_COURSE_REQUEST = "LOAD_COURSE_REQUEST"
export const LOAD_COURSE_SUCCESS = "LOAD_COURSE_SUCCESS"
export const LOAD_COURSE_FAIL = "LOAD_COURSE_FAIL"

export const PUBLISHED_COURSES_REQUEST = "PUBLISHED_COURSES_REQUEST"
export const PUBLISHED_COURSES_SUCCESS = "PUBLISHED_COURSES_SUCCESS"
export const PUBLISHED_COURSES_FAIL = "PUBLISHED_COURSES_FAIL"

export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST"
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS"
export const GET_COURSE_FAIL = "GET_COURSE_FAIL"

export const CHECK_ENROLL_REQUEST = "CHECK_ENROLL_REQUEST"
export const CHECK_ENROLL_SUCCESS = "CHECK_ENROLL_SUCCESS"
export const CHECK_ENROLL_FAIL = "CHECK_ENROLL_FAIL"

export const FREE_ENROLL_REQUEST = "FREE_ENROLL_REQUEST"
export const FREE_ENROLL_SUCCESS = "FREE_ENROLL_SUCCESS"
export const FREE_ENROLL_FAIL = "FREE_ENROLL_FAIL"

export const PAID_ENROLL_REQUEST = "PAID_ENROLL_REQUEST"
export const PAID_ENROLL_SUCCESS = "PAID_ENROLL_SUCCESS"
export const PAID_ENROLL_FAIL = "PAID_ENROLL_FAIL"

export const SINGLE_COURSE_REQUEST = "SINGLE_COURSE_REQUEST"
export const SINGLE_COURSE_SUCCESS = "SINGLE_COURSE_SUCCESS"
export const SINGLE_COURSE_FAIL = "SINGLE_COURSE_FAIL"

export const SELECT_VIDEO_REQUEST = "VIDEO_REQUEST"
export const SELECT_VIDEO_SUCCESS = "VIDEO_SUCCESS"
export const SELECT_VIDEO_FAIL = "VIDEO_FAIL"
