export const POST_LESSONS_REQUEST = "POST_LESSONS_REQUEST"
export const POST_LESSONS_SUCCESS = "POST_LESSONS_SUCCESS"
export const POST_LESSONS_FAIL = "POST_LESSONS_FAIL"

export const SELECT_VIDEO_REQUEST = "VIDEO_REQUEST"
export const SELECT_VIDEO_SUCCESS = "VIDEO_SUCCESS"
export const SELECT_VIDEO_FAIL = "VIDEO_FAIL"
